{{$player->name}}
{{$player->device}}
{{$player->nationality}}
{{$player->contract_lenght}}
{{$player->position}}
{{$player->overall}}
{{$player->age}}
{{$player->wage}}
{{$player->team->name}}
{{$player->personality->fame}}
{{$player->personality->greed}}
{{$player->personality->satisfaction}}
{{$player->personality->leadership}}